### ISSUE TITLE
BUG:太过频繁写入hitsdb

### ISSUE THREAD

**Issue by ezlhq** [aliyun/TSDB-Client#17]
问题： 
我使用异步写入接口，发现写入hitsdb的速度有些过于快了，但是每次调用hitsdb 的put接口所包含的points很少，尽管我已经将参数 batchPutTimeLimit 调到10s，但是似乎一点改变也没有，依然每秒20次以上调用hitsdb的put接口，而每次调用包含的points length都很少。

原因：
我发现作者似乎意外的搞错了nano的单位
查看 com.aliyun.hitsdb.client.consumer.BatchPutRunnable 类 的 run方法
```
long batchPutTimeLimitNano = batchPutTimeLimit*1000l;
```
这里应该改成
```
long batchPutTimeLimitNano = batchPutTimeLimit*1000000L;
```

**Comment by hujianhong** [comment]
非常感谢指出问题，我们将在下一个版本fix掉
